// items.ts
export const items = [
    {
      id: 1,
      name: "Flaming Sword",
      type: "Sword",
      price: 0.25,
      image: "/placeholder.svg?height=400&width=400",
      likes: 42,
      supply: 1,
      attributes: {
        power: 85,
        ability: "Ignite",
        level: 20,
      },
    },
    {
      id: 2,
      name: "Arcane Staff",
      type: "Staff",
      price: 0.35,
      image: "/placeholder.svg?height=400&width=400",
      likes: 38,
      supply: 3,
      attributes: {
        power: 65,
        ability: "Teleport",
        level: 25,
      },
    },
    {
      id: 3,
      name: "Health Potion",
      type: "Potion",
      price: 0.15,
      image: "/placeholder.svg?height=400&width=400",
      likes: 24,
      supply: 10,
      attributes: {
        power: 50,
        ability: "Regenerate",
        level: 5,
      },
    },
    {
      id: 4,
      name: "Frost Blade",
      type: "Sword",
      price: 0.28,
      image: "/placeholder.svg?height=400&width=400",
      likes: 31,
      supply: 5,
      attributes: {
        power: 75,
        ability: "Freeze",
        level: 18,
      },
    },
    {
      id: 5,
      name: "Lightning Staff",
      type: "Staff",
      price: 0.4,
      image: "/placeholder.svg?height=400&width=400",
      likes: 45,
      supply: 2,
      attributes: {
        power: 90,
        ability: "Shock",
        level: 30,
      },
    },
    {
      id: 6,
      name: "Invisibility Potion",
      type: "Potion",
      price: 0.18,
      image: "/placeholder.svg?height=400&width=400",
      likes: 29,
      supply: 8,
      attributes: {
        power: 40,
        ability: "Vanish",
        level: 12,
      },
    },
    {
        id: 7,
        name: "Lightning Staff",
        type: "Staff",
        price: 0.4,
        image: "/placeholder.svg?height=400&width=400",
        likes: 45,
        supply: 2,
        attributes: {
          power: 90,
          ability: "Shock",
          level: 30,
        },
      },
      {
        id: 8,
        name: "Invisibility Potion",
        type: "Potion",
        price: 0.18,
        image: "/placeholder.svg?height=400&width=400",
        likes: 29,
        supply: 8,
        attributes: {
          power: 40,
          ability: "Vanish",
          level: 12,
        },
      },
  ];
  